import Link from 'next/link';
const questions = [
  ['What can I do with OARS?', 'Keep your property information in one place, record flooding and salt-patch observations, explore map layers, and find programs or practices to discuss with a service provider.'],
  ['Do I need an account?', 'You can browse programs, view the photo guide, and explore the public map without signing in. Create a Landowner account to save properties, assessments, maps and observation photos. Drawings on the public map are temporary.'],
  ['Which account should I choose?', 'Choose Landowner to manage your own properties. Choose Agency to publish assistance programs, or Extension Officer to support assigned landowners. Agency and Extension Officer accounts need administrator approval after email verification. Landowners do not need manual approval.'],
  ['Why can’t I sign in yet?', 'Check for the email verification message, including your spam folder. Agency and Extension Officer accounts also need administrator approval. If you forgot your password, enter your email on the sign-in page and use the password reset option.'],
  ['Can I add more than one property?', 'Yes. Add each property separately in your dashboard. Select the property you want before opening its assessment or GIS explorer so its observations are kept with the correct record.'],
  ['Why is my address not found?', 'A valid address can be missing from the map service. Enter the street number, street name, postal city, state and ZIP. A historic district or neighborhood name may differ from the postal city. If the address still cannot be located, contact the OARS team; this version needs a map match before saving a new property.'],
  ['How do I record a flooding or salt-patch observation?', 'Open a saved property’s GIS explorer, select Flooding or Salt Patch, choose Add observation, then click the observed location on the map. Enter the observation date and notes. Use the exact affected location rather than the property center.'],
  ['Are my changes saved automatically?', 'Property profiles save when you choose Save property, and assessments save when you choose Save assessment. Saved-property maps autosave; wait for “All map changes saved” before leaving. The public map does not save drawings to your account.'],
  ['What should I do if my map will not save?', 'Keep the page open and use Retry save. Export your GeoJSON as a backup before reloading or discarding a draft. If another session changed the map, review the conflict message so you do not lose your observations.'],
  ['Can I attach photos?', 'Yes. Save an observation first, then choose its marker under Your observation photos and upload a JPG or PNG up to 10 MB. You can download or delete it later. Delete attached photos before removing their marker or property.'],
  ['Who can see my property observations?', 'Saved maps and observation photos are accessible to the property owner and active OARS administrators for account support and review. Assigned officers can access the property information in their portfolio, but not the owner’s private map or photos. Share exported files only with the people you intend to receive them.'],
  ['What does my SWI score mean?', 'The current score is a demonstration based on the conditions you select. It is not a measurement of salinity or a final scientific diagnosis. Use the field photo guide and discuss your observations with a qualified service provider before making land-management decisions.'],
  ['Do the map layers show conditions on my property today?', 'Not necessarily. Imagery and land-cover maps have collection dates. Flood layers may show scenarios rather than current flooding. Soil map units are not field measurements. Missing map coverage does not mean your property is unaffected.'],
  ['How do I find a relevant program?', 'Open Programs, search by topic or provider, and filter by land use, geographic scope and program/practice type. Open a listing to review eligibility, assistance, contacts and provider links. Assessment examples are starting points; they do not guarantee eligibility or funding.'],
  ['How do I apply for a program?', 'Follow the listing’s provider link or contact the organization for current instructions and deadlines. Publishing or viewing a listing in OARS does not submit an application. An Extension Officer can help track application preparation and consent.'],
  ['How do I send an observation to Salt Patch Mapper?', 'Open a salt-patch marker and choose Report this salt patch to Salt Patch Mapper. Review your name, county, location and notes, then agree to share them. Complete the external survey, attach your photo, finish CAPTCHA and submit there. Saving in OARS alone does not send a report.'],
  ['Can I print or share my results?', 'At the assessment Results step, choose Print / download results, then Download results PDF. For a saved property, the PDF can include the saved boundary, markers, notes and optional photos. Open the PDF to print it. Save your map changes first; the PDF does not include live flood layers or unsaved edits.'],
  ['Where can I learn how to use the site?', 'Select Take a tour for a guided introduction. The SWI photo guide provides larger field images and draft scorecards. You can close a tour at any time and restart it later.'],
  ['Can my organization add or update a program?', 'Approved Agency and Extension Officer accounts can manage their own program listings. Administrators can manage all contributor listings. Save a draft while preparing it, publish when ready, or change it back to Draft to remove it from public view.'],
];
export function Faqs() {
  return <section id="faqs" className="mx-auto max-w-4xl px-5 py-12"><h1 className="text-3xl font-semibold">Frequently asked questions</h1><div className="mt-6 space-y-3">{questions.map(([question,answer])=><details className="rounded-xl border bg-white p-5" key={question}><summary className="cursor-pointer font-semibold">{question}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div><p className="mt-5 text-sm">Visit the <Link className="underline" href="/swi-guide">SWI photo guide</Link>, open your <Link className="underline" href="/gis">GIS explorer</Link>, or browse <Link className="underline" href="/programs">programs</Link>.</p></section>;
}
